# Generated by Django 4.1.3 on 2023-05-24 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='server_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 24, 6, 40, 13, 593922)),
        ),
    ]
