# Generated by Django 4.1.3 on 2023-05-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_reminder_server_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='server_time',
        ),
        migrations.AlterField(
            model_name='reminder',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
