# Generated by Django 4.1.3 on 2023-08-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_remove_reminder_server_time_alter_reminder_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='entry_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='entry_type',
            field=models.CharField(blank=True, choices=[('audio', 'Audio'), ('text', 'Text')], max_length=10, null=True),
        ),
    ]
