# Generated by Django 4.1.3 on 2023-08-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_journal_entry_length_journal_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='entry_length',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='journal',
            name='entry_type',
            field=models.CharField(choices=[('audio', 'Audio'), ('text', 'Text')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
