# Generated by Django 4.1.3 on 2023-08-12 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_alter_journal_entry_length_alter_journal_entry_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='entry_length',
        ),
    ]
