# Generated by Django 4.1.3 on 2023-08-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_remove_journal_entry_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='entry_length',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='entry_type',
            field=models.CharField(choices=[('audio', 'Audio'), ('text', 'Text')], max_length=10, null=True),
        ),
    ]
