# Generated by Django 4.1.3 on 2023-08-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_journal_entry_length_alter_journal_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio_files/'),
        ),
    ]
