# Generated by Django 4.1.3 on 2023-08-12 17:44

from django.db import migrations, models
import journal.models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_alter_journal_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=journal.models.name_file),
        ),
    ]
