# Generated by Django 4.1.3 on 2023-09-13 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_alter_journal_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='entry_type',
        ),
    ]
