# Generated by Django 4.1.3 on 2023-09-13 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaks', '0002_remove_streaksaveruse_used_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streaksaveruse',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
