# Generated by Django 4.1.3 on 2023-09-15 14:04

import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to=cms.models.name_file)),
                ('coinvalue', models.IntegerField(blank=True, null=True)),
                ('entryrange', models.CharField(blank=True, max_length=100, null=True)),
                ('coinvalue1', models.IntegerField(blank=True, null=True)),
                ('entryrange1', models.CharField(blank=True, max_length=100, null=True)),
                ('coinvalue2', models.IntegerField(blank=True, null=True)),
                ('entryrange2', models.CharField(blank=True, max_length=100, null=True)),
                ('coming_soon', models.BooleanField()),
            ],
            options={
                'db_table': 'coin_detail',
            },
        ),
    ]
