# Generated by Django 4.1.3 on 2023-09-13 08:02

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField()),
                ('repeat', models.CharField(choices=[('Once', 'Once'), ('Everyday', 'Everyday'), ('Custom', 'Custom')], default='Everyday', max_length=50)),
                ('days_of_week', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), size=7)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Reminder',
            },
        ),
    ]
