# Generated by Django 4.1.3 on 2023-09-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coins_balance',
            field=models.IntegerField(default=0),
        ),
    ]
