# Generated by Django 4.1.3 on 2023-04-14 06:40

from django.db import migrations, models
import prompts.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to=prompts.models.nameFile)),
                ('image', models.ImageField(blank=True, null=True, upload_to=prompts.models.nameFile)),
                ('sentiments', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Prompt',
            },
        ),
    ]
